### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by Facyla** [ColdTrick/uservalidationbyadmin#2]
Hi,

I used to have my own fork from TeamWebgalli version, and am considering moving to your version (for Elgg 1.11+) - mainly for the non-admin validation role.
But i would miss 3 features i had added and think are very helpful, mainly related to notifications :

1) Admin can validate accounts through a direct link, without being logged in (to be frank, i haven't checked if your plugin already does that too). Main use was validating on the phone, while in the train, low connection, etc.
Note I had not implemented direct link user delete because a mistake cannot be repaired in that case...

2) Admin notifications include some more information for direct validation, including user email, username and full name, plus IP address and guessed geolocation (these 2 latest were nice founds from Team Webgalli version). Those are usually very helpful to validate account when there is spam.

3) Validated users receive an improved notification, including their username - which they often tend to forget. It also says something like "Password : the one you have chosen at registration time". 
I would actually add the registration email and link to regenerate password now, so they can keep that email as a reminder and refer to it.

Well, i have now 2 options : upgrading my plugin to 1.11, or submit a few patches to yours to add these features if you agree ?

Yours,
Florian

**Comment by jdalsem** [comment]
Florian, i can agree on all the features, however if you are willing to add them consider putting all the "extended information" in the emails behind a plugin setting. Not all admins would like to have all that information exposed

**Comment by Facyla** [comment]
Sure, i can add a setting for each of these. I prefer building on a common base with settings than maintain a parallel version that provide basically the same features...
Some PR should be coming soon ;)

**Comment by Facyla** [comment]
Most features implemented, except geolocation information.
Settings are implemented so that previous behaviour remains default.
Tested successfully on 1.12.5, but should work fine on 1.10.x and 1.11.x

Hope you'll like it :)

**Comment by Facyla** [comment]
Geolocation is now added to the PR

**Comment by jdalsem** [comment]
user validation by admin is now part of Elgg core. This plugin is now archived
